function generate_lookup_tables(outputDir)
%GENERATE_LOOKUP_TABLES Generate firmware-compatible DAC lookup tables.
%   GENERATE_LOOKUP_TABLES() writes lookup_tables.h and lookup_tables.csv
%   under scripts/generated. GENERATE_LOOKUP_TABLES(OUTPUTDIR) selects a
%   different output directory.

    if nargin < 1
        scriptDir = fileparts(mfilename('fullpath'));
        outputDir = fullfile(scriptDir, 'generated');
    end

    sampleRate = 1e6;
    points = 200;
    frequencies = 10e3:5e3:100e3;
    offset = 2048;
    amplitude = 1500;
    dacMaximum = 4095;

    sampleTime = (1:points) / sampleRate; % Original table starts at 1/fs.
    sineTable = zeros(numel(frequencies), points);
    cosineTable = zeros(numel(frequencies), points);
    triangleTable = zeros(numel(frequencies), points);

    for row = 1:numel(frequencies)
        phase = 2 * pi * frequencies(row) * sampleTime;
        sineTable(row, :) = quantize(offset + amplitude * sin(phase), dacMaximum);
        cosineTable(row, :) = quantize(offset + amplitude * cos(phase), dacMaximum);
        triangle = (2 / pi) * asin(sin(phase - pi / 2));
        triangleTable(row, :) = quantize(offset + amplitude * triangle, dacMaximum);
    end

    if ~exist(outputDir, 'dir')
        mkdir(outputDir);
    end

    headerPath = fullfile(outputDir, 'lookup_tables.h');
    csvPath = fullfile(outputDir, 'lookup_tables.csv');
    writeHeader(headerPath, frequencies, sineTable, cosineTable, triangleTable);
    writeCsv(csvPath, frequencies, sineTable, cosineTable, triangleTable);

    fprintf('Generated %d frequencies x %d points\n', numel(frequencies), points);
    fprintf('%s\n%s\n', headerPath, csvPath);
end

function values = quantize(values, maximum)
    values = min(maximum, max(0, floor(values + 0.5)));
end

function writeHeader(path, frequencies, sineTable, cosineTable, triangleTable)
    file = fopen(path, 'w');
    assert(file ~= -1, 'Unable to open %s', path);
    cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>

    fprintf(file, '/* Generated by generate_lookup_tables.m. Do not edit manually. */\n');
    fprintf(file, '#ifndef GENERATED_LOOKUP_TABLES_H\n#define GENERATED_LOOKUP_TABLES_H\n\n');
    fprintf(file, '#include <stdint.h>\n\n');
    fprintf(file, '#define LOOKUP_FREQUENCY_COUNT %d\n', numel(frequencies));
    fprintf(file, '#define LOOKUP_POINTS_PER_FREQUENCY %d\n\n', size(sineTable, 2));
    writeArray(file, 'DAC_SIN', frequencies, sineTable);
    writeArray(file, 'DAC_COS', frequencies, cosineTable);
    writeArray(file, 'Tri_Wave', frequencies, triangleTable);
    fprintf(file, '#endif /* GENERATED_LOOKUP_TABLES_H */\n');
end

function writeArray(file, name, frequencies, values)
    rows = size(values, 1);
    points = size(values, 2);
    fprintf(file, 'static const uint16_t %s[%d * %d] = {\n', name, rows, points);
    for row = 1:rows
        fprintf(file, '    /* %.0f Hz */\n', frequencies(row));
        for first = 1:12:points
            last = min(first + 11, points);
            fprintf(file, '    ');
            fprintf(file, '%d', values(row, first));
            for column = first + 1:last
                fprintf(file, ', %d', values(row, column));
            end
            if row < rows || last < points
                fprintf(file, ',');
            end
            fprintf(file, '\n');
        end
    end
    fprintf(file, '};\n\n');
end

function writeCsv(path, frequencies, sineTable, cosineTable, triangleTable)
    file = fopen(path, 'w');
    assert(file ~= -1, 'Unable to open %s', path);
    cleanup = onCleanup(@() fclose(file)); %#ok<NASGU>

    fprintf(file, 'frequency_hz,sample_index,sine,cosine,triangle\n');
    for row = 1:numel(frequencies)
        for column = 1:size(sineTable, 2)
            fprintf(file, '%.0f,%d,%d,%d,%d\n', frequencies(row), column - 1, ...
                sineTable(row, column), cosineTable(row, column), triangleTable(row, column));
        end
    end
end
