#!/usr/bin/env python3
"""Generate the sine, cosine, and triangle lookup tables used by the firmware."""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path
from typing import Iterable


def quantize(value: float, dac_bits: int) -> int:
    """Round a non-negative value to the nearest DAC code and saturate it."""
    maximum = (1 << dac_bits) - 1
    return min(maximum, max(0, math.floor(value + 0.5)))


def generate_tables(
    sample_rate: float,
    points: int,
    frequencies: Iterable[float],
    offset: float,
    amplitude: float,
    dac_bits: int,
) -> tuple[list[float], list[list[int]], list[list[int]], list[list[int]]]:
    frequencies = list(frequencies)
    sine: list[list[int]] = []
    cosine: list[list[int]] = []
    triangle: list[list[int]] = []

    for frequency in frequencies:
        sine_row: list[int] = []
        cosine_row: list[int] = []
        triangle_row: list[int] = []
        for index in range(points):
            # The original firmware table starts at t = 1 / fs, not t = 0.
            phase = 2.0 * math.pi * frequency * (index + 1) / sample_rate
            sine_row.append(quantize(offset + amplitude * math.sin(phase), dac_bits))
            cosine_row.append(quantize(offset + amplitude * math.cos(phase), dac_bits))
            triangle_value = (2.0 / math.pi) * math.asin(math.sin(phase - math.pi / 2.0))
            triangle_row.append(quantize(offset + amplitude * triangle_value, dac_bits))
        sine.append(sine_row)
        cosine.append(cosine_row)
        triangle.append(triangle_row)

    return frequencies, sine, cosine, triangle


def format_frequency(frequency: float) -> str:
    return str(int(frequency)) if frequency.is_integer() else f"{frequency:g}"


def write_c_array(stream, name: str, rows: list[list[int]], frequencies: list[float]) -> None:
    points = len(rows[0])
    stream.write(f"static const uint16_t {name}[{len(rows)} * {points}] = {{\n")
    for frequency, row in zip(frequencies, rows):
        stream.write(f"    /* {format_frequency(frequency)} Hz */\n")
        for start in range(0, points, 12):
            values = ", ".join(str(value) for value in row[start : start + 12])
            comma = "," if start + 12 < points or frequency != frequencies[-1] else ""
            stream.write(f"    {values}{comma}\n")
    stream.write("};\n\n")


def write_header(
    path: Path,
    frequencies: list[float],
    sine: list[list[int]],
    cosine: list[list[int]],
    triangle: list[list[int]],
) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("/* Generated by generate_lookup_tables.py. Do not edit manually. */\n")
        stream.write("#ifndef GENERATED_LOOKUP_TABLES_H\n#define GENERATED_LOOKUP_TABLES_H\n\n")
        stream.write("#include <stdint.h>\n\n")
        stream.write(f"#define LOOKUP_FREQUENCY_COUNT {len(frequencies)}\n")
        stream.write(f"#define LOOKUP_POINTS_PER_FREQUENCY {len(sine[0])}\n\n")
        write_c_array(stream, "DAC_SIN", sine, frequencies)
        write_c_array(stream, "DAC_COS", cosine, frequencies)
        write_c_array(stream, "Tri_Wave", triangle, frequencies)
        stream.write("#endif /* GENERATED_LOOKUP_TABLES_H */\n")


def write_csv(
    path: Path,
    frequencies: list[float],
    sine: list[list[int]],
    cosine: list[list[int]],
    triangle: list[list[int]],
) -> None:
    with path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream)
        writer.writerow(["frequency_hz", "sample_index", "sine", "cosine", "triangle"])
        for row_index, frequency in enumerate(frequencies):
            for sample_index in range(len(sine[row_index])):
                writer.writerow(
                    [
                        format_frequency(frequency),
                        sample_index,
                        sine[row_index][sample_index],
                        cosine[row_index][sample_index],
                        triangle[row_index][sample_index],
                    ]
                )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).parent / "generated")
    parser.add_argument("--sample-rate", type=float, default=1_000_000.0, help="sample rate in Hz")
    parser.add_argument("--points", type=int, default=200, help="samples per frequency")
    parser.add_argument("--min-frequency", type=float, default=10_000.0, help="first frequency in Hz")
    parser.add_argument("--max-frequency", type=float, default=100_000.0, help="last frequency in Hz")
    parser.add_argument("--frequency-step", type=float, default=5_000.0, help="frequency step in Hz")
    parser.add_argument("--offset", type=float, default=2048.0, help="DAC center code")
    parser.add_argument("--amplitude", type=float, default=1500.0, help="DAC peak amplitude in codes")
    parser.add_argument("--dac-bits", type=int, default=12, help="DAC resolution")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.sample_rate <= 0 or args.points <= 0 or args.frequency_step <= 0 or args.dac_bits <= 0:
        raise SystemExit("sample rate, points, frequency step, and DAC bits must be positive")
    if args.min_frequency <= 0 or args.max_frequency < args.min_frequency:
        raise SystemExit("invalid frequency range")
    if args.offset < 0 or args.amplitude < 0:
        raise SystemExit("offset and amplitude must be non-negative")

    count = int(math.floor((args.max_frequency - args.min_frequency) / args.frequency_step + 1e-12)) + 1
    frequencies = [args.min_frequency + index * args.frequency_step for index in range(count)]
    if not math.isclose(frequencies[-1], args.max_frequency, rel_tol=0.0, abs_tol=1e-9):
        raise SystemExit("frequency range must be divisible by frequency step")

    frequencies, sine, cosine, triangle = generate_tables(
        args.sample_rate,
        args.points,
        frequencies,
        args.offset,
        args.amplitude,
        args.dac_bits,
    )
    args.output_dir.mkdir(parents=True, exist_ok=True)
    header_path = args.output_dir / "lookup_tables.h"
    csv_path = args.output_dir / "lookup_tables.csv"
    write_header(header_path, frequencies, sine, cosine, triangle)
    write_csv(csv_path, frequencies, sine, cosine, triangle)
    print(f"Generated {len(frequencies)} frequencies x {args.points} points")
    print(header_path)
    print(csv_path)


if __name__ == "__main__":
    main()
